name: Update Semver

on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: haya14busa/action-update-semver@v1
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
